### ISSUE TITLE
Option for reverse input on the PIN CODE screen or 0(or random) as the first typed number that doesn't count as an input

### ISSUE THREAD

**Issue by malnsk** [holtiwilan/OpenSourceHackerMagicDevice#5]
Whenever i perform i always need to rethink the first input for suits. I know the memorization is simple, since you use the suit symbol shape to interpret the number. But i always stop for a second to rethink if it's correct. Since the value corresponds directly to a number, the first input could be the value. I know it creates a problem for instance if you input JACK QUEEN or KING since it's 11, 12 or 13. but maybe we can input JACK of SPADES as 1#1, so we tell the program the first input is a single number.

The other option as mentioned in the title is that the first input could be 0 or even a random number, so at the end we input 4 numbers, making the first input a random input that doesn't count as an input and would make the typing more fluid during the patter or would make the time to rethink the suit input easier.

I hope it makes sense :).

Kind regards
Luka

**Comment by holtiwilan** [comment]
Should be possible.
Will add a setting to reverse the entry of value and suit.
The first digit can be anything, because it doesn't matter.
Will be a feature in the next release

**Comment by holtiwilan** [comment]
https://github.com/holtiwilan/OpenSourceHackerMagicDevice/releases/tag/v1.6
